{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-10",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "43996156",
        "Fixer": "61599526"
    },
    "Package": {
        "Registry": "pip",
        "Name": "ray",
        "URL": "https://pypi.org/project/ray",
        "Downloads": "31706"
    },
    "CWEs": [
        {
            "ID": "CWE-94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "",
        "AC": "",
        "PR": "",
        "UI": "",
        "S": "",
        "C": "",
        "I": "",
        "A": "",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "8.3"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/ray-project/ray",
        "Codebase": [
            "Python"
        ],
        "Owner": "ray-project",
        "Name": "ray",
        "Forks": "2354",
        "Stars": "14647"
    },
    "Permalinks": [
        "https://user-images.githubusercontent.com/43996156/103398598-65669800-4b63-11eb-8386-0f62c5ce185f.png"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1505",
    "FixSubmissionCount": 1
}