{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-02-23",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "61599526",
        "Fixer": ""
    },
    "Package": {
        "Registry": "pip",
        "Name": "soda-sql",
        "URL": "https://pypi.org/project/soda-sql",
        "Downloads": "81"
    },
    "CWEs": [
        {
            "ID": "94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3",
        "AV": "N",
        "AC": "L",
        "PR": "L",
        "UI": "N",
        "S": "U",
        "C": "H",
        "I": "H",
        "A": "H",
        "E": "X",
        "RL": "X",
        "RC": "X",
        "Score": "8.8"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/sodadata/soda-sql",
        "Codebase": [
            "Python"
        ],
        "Owner": "sodadata",
        "Name": "soda-sql",
        "Forks": "10",
        "Stars": "123",
        "ForkName": "soda-sql"
    },
    "Permalinks": [
        ""
    ],
    "References": [
        {
            "Description": "https://drive.google.com/file/d/1KQ6IiYF8ipZujRKfWUgexz8MdXJfqEdI/view?usp=sharing",
            "URL": ""
        }
    ],
    "PrNumber": "1953",
    "FixSubmissionCount": 1
}