{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-04",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "61599526",
        "Fixer": "29670330"
    },
    "Package": {
        "Registry": "pip",
        "Name": "petastorm",
        "URL": "https://pypi.org/project/petastorm",
        "Downloads": "8864"
    },
    "CWEs": [
        {
            "ID": "94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "",
        "AC": "",
        "PR": "",
        "UI": "",
        "S": "",
        "C": "",
        "I": "",
        "A": "",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "8.3"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/uber/petastorm",
        "Codebase": [
            "Python"
        ],
        "Owner": "uber",
        "Name": "petastorm",
        "Forks": "186",
        "Stars": "1064"
    },
    "Permalinks": [
        "https://drive.google.com/file/d/1m9ZfNYmMtG-9Wqubpggm2pCHon1Qa_3R/view?usp=sharing"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1445",
    "FixSubmissionCount": 1
}