{
    "PackageVulnerabilityID": "1",
    "DisclosureDate": "2021-01-04",
    "AffectedVersionRange": "*",
    "Summary": "Arbitrary Code Execution",
    "Contributor": {
        "Discloser": "61599526",
        "Fixer": "29670330"
    },
    "Package": {
        "Registry": "pip",
        "Name": "petastorm",
        "URL": "https://pypi.org/project/petastorm",
        "Downloads": "8305"
    },
    "CWEs": [
        {
            "ID": "94",
            "Description": "Arbitrary Code Execution"
        }
    ],
    "CVSS": {
        "Version": "3.1",
        "AV": "P",
        "AC": "H",
        "PR": "L",
        "UI": "N",
        "S": "U",
        "C": "L",
        "I": "L",
        "A": "L",
        "E": "",
        "RL": "",
        "RC": "",
        "Score": "3.8"
    },
    "CVEs": [
        ""
    ],
    "Repository": {
        "URL": "https://github.com/uber/petastorm",
        "Codebase": [
            "Python"
        ],
        "Owner": "uber",
        "Name": "petastorm",
        "Forks": "187",
        "Stars": "1081",
        "ForkName": "petastorm"
    },
    "Permalinks": [
        "https://drive.google.com/file/d/1m9ZfNYmMtG-9Wqubpggm2pCHon1Qa_3R/view?usp=sharing"
    ],
    "References": [
        {
            "Description": "",
            "URL": ""
        }
    ],
    "PrNumber": "1445",
    "FixSubmissionCount": 1
}